micronaut:
#  ssl:
#    enabled: false
#    key-store:
#      path: classpath:hornsup-raspi-finance-keystore.jks
#      type: JKS
#      password: monday1
#    # buildSelfSigned: true
#    port: 8080
  server:
    #dualProtocol: true
    port: 8443
    cors:
      enabled: true
  application:
    name: raspi-finance-enpoint-micronaut
  metrics:
    enabled: true

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/finance_test_db
    driverClassName: org.postgresql.Driver
    username: henninb
    password: monday1
    schema-generate: NONE
    dialect: Postgres

#jpa:
#  default:
#    entity-scan:
#      packages: finance.domain
#    properties:
#      hibernate:
##        bytecode:
##          provider: none
#        hbm2ddl:
#          auto: validate
#        show_sql: true

