micronaut:
  ssl:
    enabled: true
    port: 8443
    key-store:
      path: classpath:bhenning-letsencrypt.p12
      password: ${SSL_KEY_STORE_PASSWORD}
      type: PKCS12
    key-alias: bhenning
    protocol: TLS
  server:
    port: -1
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - "https://localhost:3000"
            - "https://localhost:4200"
            - "https://hornsup:3000"
            - "https://finance.lan"
            - "https://www.bhenning.com"
            - "https://www.brianhenning.com"
          allowedMethods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          allowedHeaders:
            - "Content-Type"
            - "Authorization"
            - "X-Requested-With"
          allowCredentials: true
  application:
    name: raspi-finance-endpoint-micronaut
  metrics:
    enabled: true
  endpoints:
    health:
      enabled: true
      sensitive: false
  graphql:
    enabled: true
    path: /graphql

datasources:
  default:
    url: ${DATASOURCE:jdbc:postgresql://192.168.10.10:5432/finance_db}
    driverClassName: org.postgresql.Driver
    username: ${DATASOURCE_USERNAME:henninb}
    password: ${DATASOURCE_PASSWORD}
    schema-generate: NONE
    dialect: Postgres

custom:
  project:
    jwt:
      key: ${JWT_KEY}

jpa:
  default:
    entity-scan:
      packages: 'finance.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

